### ISSUE TITLE
Error doing job: Unclosed client session

### ISSUE THREAD

**Issue by kroimon** [zhelev/python-afsapi#1]
I have a MEDION LIFE P85025 (MD 86955). The device is loaded into home assistant as expected and correctly shows the current state and allows controlling the radio. However, the hass log is spammed with the following exception every few seconds:

```
2018-05-01 15:25:50 INFO (MainThread) [root] AFSAPI Exception: Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.5/site-packages/afsapi/__init__.py", line 95, in call
    self.sid = yield from self.create_session()
  File "/opt/homeassistant/lib/python3.5/site-packages/afsapi/__init__.py", line 84, in create_session
    doc = objectify.fromstring(text)
  File "src/lxml/objectify.pyx", line 1801, in lxml.objectify.fromstring
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1757, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1067, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 710, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 639, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

2018-05-01 15:25:50 ERROR (MainThread) [homeassistant.core] Error doing job: Unclosed client session
```

What information can I collect to help debugging this issue?

**Comment by johnjones** [comment]
I also have the problem of unclosed client sessions which is frustrating in the extreme 👍 
 [homeassistant.core] Error doing job: Unclosed client session
 [homeassistant.core] Error doing job: Unclosed client session
 [homeassistant.core] Error doing job: Unclosed client session

This is present on python 3.6.5 with the latest lxml etc 

I believe @zhelev contributed the home assistant code, would you be so kind to update it to close the session or simply reuse the open session ?

see : https://github.com/home-assistant/home-assistant/issues/13099
